### ISSUE TITLE
What does the app do?

### ISSUE THREAD

**Issue by axelsimon** [SagerNet/SagerNet#485]
### Describe the bug

There is no real information as to why i should use (or not use) SagerNet

### To Reproduce
Browse the website, read the README: all you get is "The universal proxy toolchain for Android, written in Kotlin.".
As a potential user, this tells me nearly nothing.

What can i do with this? What problems does it solve? What is not designed to help with? etc.

### Expected behavior

Explain why the app is useful and in what problems it helps solve.

**Comment by linsui** [comment]
If you don't know what it is, then you are likely not a potential user. This is an Android client for Shadowsocks/V2Ray and other tools. If you don't use them, you don't need this app.

**Comment by axelsimon** [comment]
So this is like the Fight Club of apps, if you don't know, you don't need to know?
But seriously, the app is on F-Droid, a general app provider. It's only fair to put a little bit of effort into explaining what the app does.
Otherwise, people who could benefit from the app might not be able to know it exists and can help them. Isn't that counter-productive?

**Comment by iKirby** [comment]
This is an app that can help you bypass internet restrictions. There are some regions in the world where many websites and services are blocked. Pepole developed a lot of apps to bypass these restrictions, and this app is one of them.

You may want to ask, why not use a VPN? It is because normal VPNs can be detected and blocked. This app features many protocols that are hard to detect and block, to help people access the internet. 

It is not designed to provide much anonymity, so if you need to hide your activity from the internet, use something like Tor or I2P.

This app may still be useful if you want to change your IP address, for example, to bypass some restrictions on streaming sites. If you want to try it out, you can install one of the corresponding server apps on your VPS, and connect to it using SagerNet.

**Comment by axelsimon** [comment]
Thanks. Yes, i know what SSH, Wireguard and Shadowsocks are :) I think the description you've just shared should be used as the basis for a better README, more people need to have access to these tools and the first step to this is to present them in a way that is understandable by many.

**Comment by linsui** [comment]
If you find it from F-Droid you'll see https://github.com/SagerNet/SagerNet/blob/dev/metadata/en-US/description.txt first. It's better than the readme. You can open a PR to improve the readme and the description.

**Comment by klzgrad** [comment]
Yes, this is the Fight Club of an app. Don't want to attract too much attention. Don't have enough resource for noob support.
